# Generated by Django 2.1.5 on 2019-01-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'flowers',
            },
        ),
    ]
