# Generated by Django 2.2.9 on 2020-01-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='type',
        ),
    ]
